# See https://docs.aspect.build/workflows/configuration
tasks:
  - lint:
      queue: aspect-medium
  - format:
      queue: aspect-medium
  - buildifier:
      queue: aspect-medium
  - configure:
      queue: aspect-medium
  - test:
  - finalization:
      queue: aspect-small
notifications:
  github: {}
