# See https://docs.aspect.build/workflows/configuration
tasks:
  - format:
      queue: aspect-medium
  - buildifier:
      queue: aspect-medium
  - configure:
      queue: aspect-medium
  - test:
      targets:
        - //...
        # Disable e2e tests while ethereal mail is down
        # https://github.com/nodemailer/nodemailer/issues/1710
        - -//e2e:test
  - finalization:
      queue: aspect-small
notifications:
  github: {}
